apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kibana-secret
spec:
  secretName: kibana-secret
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer
  commonName: kibana.melkouhen.net
  dnsNames:
  - kibana.melkouhen.net
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
        - kibana.melkouhen.net