apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-master-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /zpool-126262/WWWLOGSTASH/master-1
    server: 10.16.103.9
  claimRef:
    namespace: {{ .Values.environment }}
    name: data-elasticstack-elasticsearch-master-1
  persistentVolumeReclaimPolicy: Delete