apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tls
spec:
  secretName: {{ .Release.Name }}-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: {{ .Release.Name }}.melkouhen.net
  dnsNames:
    - {{ .Release.Name }}.melkouhen.net
    - registry-{{ .Release.Name }}.melkouhen.net
  acme:
    config:
      - dns01:
          provider: dns
        domains:
          - {{ .Release.Name }}.melkouhen.net
          - registry-{{ .Release.Name }}.melkouhen.net