apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Release.Name }}-sonatype-nexus-data
  awsElasticBlockStore:
    volumeID: vol-0819d7e7ec8ca001f
    fsType: ext4
  persistentVolumeReclaimPolicy: Recycle