apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Release.Name }}
  awsElasticBlockStore:
    volumeID: vol-0e242afa88660c3bb
    fsType: ext4
  persistentVolumeReclaimPolicy: Recycle